local helpers = require("tests.helpers")
local assert_type = helpers.assert_type
local assert_boolean = helpers.assert_boolean
local assert_table = helpers.assert_table
local run = helpers.run
local skip = helpers.skip

local pgConfig = {
    enabled = true,
    conninfo = ""
}

run("Postgres table exists", function()
    assert_table(Postgres, "Postgres")
end)

if not pgConfig.enabled then
    skip("Postgres suite", "set pgConfig.enabled = true to run Postgres tests")
    return
end

local pg

run("Postgres.Connect returns instance", function()
    pg = Postgres.Connect(pgConfig.conninfo)
    assert(pg, "Postgres.Connect returned nil")
    assert_type(pg, "userdata", "Postgres connection")
end)

if not pg then
    skip("Postgres suite", "connection failed, skipping remaining tests")
    return
end

run("Postgres tostring", function()
    local s = tostring(pg)
    assert(type(s) == "string" and s:find("Postgres:"), "tostring did not return expected format, got: " .. tostring(s))
end)

run("Postgres.IsBusy returns false when idle", function()
    assert_boolean(pg:IsBusy(), "IsBusy")
    assert(pg:IsBusy() == false, "expected IsBusy to be false when idle")
end)

run("Postgres.Query CREATE TABLE", function()
    local ok, err = pg:Query("CREATE TABLE IF NOT EXISTS kitsune_test (id SERIAL PRIMARY KEY, name TEXT, value DOUBLE PRECISION, flag BOOLEAN, num INT)")
    assert(ok, "Query failed: " .. tostring(err))
    local result, qerr = pg:GetResult()
    assert(result ~= nil or qerr == nil, "CREATE TABLE error: " .. tostring(qerr))
end)

run("Postgres.Query INSERT", function()
    local ok, err = pg:Query("INSERT INTO kitsune_test (name, value, flag, num) VALUES ('hello', 3.14, true, 42), ('world', 2.71, false, 100)")
    assert(ok, "Query failed: " .. tostring(err))
    local result, qerr = pg:GetResult()
    assert(result ~= nil or qerr == nil, "INSERT error: " .. tostring(qerr))
end)

run("Postgres.Query SELECT all rows", function()
    local ok, err = pg:Query("SELECT id, name, value, flag, num FROM kitsune_test ORDER BY id")
    assert(ok, "Query failed: " .. tostring(err))
    local rows, qerr = pg:GetResult()
    assert(rows, "GetResult error: " .. tostring(qerr))
    assert_table(rows, "rows")
    assert(#rows >= 2, "expected at least 2 rows, got " .. tostring(#rows))
    local row = rows[1]
    assert_table(row, "row[1]")
    assert(row[2] == "hello", "expected name='hello', got: " .. tostring(row[2]))
    assert(type(row[3]) == "number", "expected value to be number, got: " .. type(row[3]))
    assert(row[4] == true, "expected flag=true, got: " .. tostring(row[4]))
    assert(row[5] == 42, "expected num=42, got: " .. tostring(row[5]))
end)

run("Postgres.GetResultRow iterates rows", function()
    local ok, err = pg:Query("SELECT name FROM kitsune_test ORDER BY id")
    assert(ok, "Query failed: " .. tostring(err))
    local row1 = pg:GetResultRow()
    assert_table(row1, "row1")
    assert(row1[1] == "hello", "expected 'hello', got: " .. tostring(row1[1]))
    local row2 = pg:GetResultRow()
    assert_table(row2, "row2")
    assert(row2[1] == "world", "expected 'world', got: " .. tostring(row2[1]))
    local done = pg:GetResultRow()
    assert(done == nil, "expected nil after last row, got: " .. tostring(done))
end)

run("Postgres.GetResultFields returns field metadata", function()
    local ok, err = pg:Query("SELECT id, name, value, flag, num FROM kitsune_test LIMIT 1")
    assert(ok, "Query failed: " .. tostring(err))
    local fields, qerr = pg:GetResultFields()
    assert(fields, "GetResultFields error: " .. tostring(qerr))
    assert_table(fields, "fields")
    assert(#fields == 5, "expected 5 fields, got " .. tostring(#fields))
    assert(fields[1].name == "id", "expected field[1].name='id', got: " .. tostring(fields[1].name))
    assert(fields[2].name == "name", "expected field[2].name='name', got: " .. tostring(fields[2].name))
    assert(type(fields[1].type) == "number", "expected field type to be number OID")
    pg:GetResult()
end)

run("Postgres.QueryParams parameterized query", function()
    local ok, err = pg:QueryParams("SELECT name, num FROM kitsune_test WHERE name = $1", "hello")
    assert(ok, "QueryParams failed: " .. tostring(err))
    local rows, qerr = pg:GetResult()
    assert(rows, "GetResult error: " .. tostring(qerr))
    assert(#rows == 1, "expected 1 row, got " .. tostring(#rows))
    assert(rows[1][1] == "hello", "expected 'hello', got: " .. tostring(rows[1][1]))
    assert(rows[1][2] == 42, "expected 42, got: " .. tostring(rows[1][2]))
end)

run("Postgres.QueryParams with multiple params", function()
    local ok, err = pg:QueryParams("SELECT name FROM kitsune_test WHERE name = $1 OR num = $2 ORDER BY id", "world", 42)
    assert(ok, "QueryParams failed: " .. tostring(err))
    local rows, qerr = pg:GetResult()
    assert(rows, "GetResult error: " .. tostring(qerr))
    assert(#rows == 2, "expected 2 rows, got " .. tostring(#rows))
end)

run("Postgres.QueryParams with nil param (NULL)", function()
    local ok, err = pg:QueryParams("INSERT INTO kitsune_test (name, value, flag, num) VALUES ($1, $2, $3, $4)", "nulltest", nil, nil, nil)
    assert(ok, "QueryParams failed: " .. tostring(err))
    local result, qerr = pg:GetResult()
    assert(result ~= nil or qerr == nil, "INSERT with nulls error: " .. tostring(qerr))
end)

run("Postgres non-SELECT command returns empty table", function()
    local ok, err = pg:Query("UPDATE kitsune_test SET num = 999 WHERE name = 'world'")
    assert(ok, "Query failed: " .. tostring(err))
    local result, qerr = pg:GetResult()
    assert(result ~= nil, "UPDATE should return empty table, not nil. error: " .. tostring(qerr))
    assert(type(result) == "table", "expected table, got: " .. type(result))
    assert(#result == 0, "expected empty table from UPDATE, got " .. tostring(#result) .. " rows")
end)

run("Postgres empty SELECT returns empty table", function()
    local ok, err = pg:Query("SELECT * FROM kitsune_test WHERE name = 'this_name_does_not_exist'")
    assert(ok, "Query failed: " .. tostring(err))
    local result, qerr = pg:GetResult()
    assert(result ~= nil, "empty SELECT should return empty table, not nil. error: " .. tostring(qerr))
    assert(type(result) == "table", "expected table, got: " .. type(result))
    assert(#result == 0, "expected 0 rows, got " .. tostring(#result))
end)

run("Postgres GetResult clears result on second call", function()
    local ok, err = pg:Query("SELECT name FROM kitsune_test ORDER BY id LIMIT 1")
    assert(ok, "Query failed: " .. tostring(err))
    local r1, e1 = pg:GetResult()
    assert(r1 ~= nil, "first GetResult should return rows, not nil")
    local r2, e2 = pg:GetResult()
    assert(r2 == nil, "second GetResult should return nil after result is consumed")
    assert(e2 == "no result", "expected 'no result' error, got: " .. tostring(e2))
end)

run("Postgres GetResultRow clears result when exhausted", function()
    local ok, err = pg:Query("SELECT name FROM kitsune_test WHERE name = 'hello' ORDER BY id")
    assert(ok, "Query failed: " .. tostring(err))
    local row = pg:GetResultRow()
    assert(row ~= nil, "expected a row")
    local done = pg:GetResultRow()
    assert(done == nil, "expected nil to signal end of results")
    local r2, e2 = pg:GetResult()
    assert(r2 == nil, "GetResult after exhausted GetResultRow should return nil")
    assert(e2 == "no result", "expected 'no result', got: " .. tostring(e2))
end)

run("Postgres sequential queries clear previous result", function()
    local ok1, e1 = pg:Query("SELECT name FROM kitsune_test WHERE name = 'hello' ORDER BY id")
    assert(ok1, "first query failed: " .. tostring(e1))
    local r1 = pg:GetResult()
    assert(r1 and #r1 >= 1, "first query should return rows")

    local ok2, e2 = pg:Query("SELECT name FROM kitsune_test WHERE name = 'world' ORDER BY id")
    assert(ok2, "second query failed: " .. tostring(e2))
    local r2 = pg:GetResult()
    assert(r2 and #r2 >= 1, "second query should return rows")
    assert(r2[1][1] == "world", "expected 'world', got: " .. tostring(r2[1][1]))
end)

run("Postgres QueryParams with number param", function()
    local ok, err = pg:QueryParams("SELECT name FROM kitsune_test WHERE num = $1", 42)
    assert(ok, "QueryParams failed: " .. tostring(err))
    local rows, qerr = pg:GetResult()
    assert(rows, "GetResult error: " .. tostring(qerr))
    assert(#rows >= 1, "expected at least 1 row, got " .. tostring(#rows))
    assert(rows[1][1] == "hello", "expected 'hello', got: " .. tostring(rows[1][1]))
end)

run("Postgres INSERT RETURNING returns rows", function()
    local ok, err = pg:Query("INSERT INTO kitsune_test (name, num) VALUES ('returning_test', 55) RETURNING id, name")
    assert(ok, "Query failed: " .. tostring(err))
    local rows, qerr = pg:GetResult()
    assert(rows, "GetResult error: " .. tostring(qerr))
    assert(#rows == 1, "expected 1 row from RETURNING, got " .. tostring(#rows))
    assert(type(rows[1][1]) == "number", "RETURNING id should be integer, got: " .. type(rows[1][1]))
    assert(rows[1][2] == "returning_test", "RETURNING name mismatch: " .. tostring(rows[1][2]))
end)

run("Postgres GetResultFields with GetResultRow", function()
    local ok, err = pg:Query("SELECT id, name, num FROM kitsune_test WHERE name = 'hello' LIMIT 1")
    assert(ok, "Query failed: " .. tostring(err))
    local fields, ferr = pg:GetResultFields()
    assert(fields, "GetResultFields error: " .. tostring(ferr))
    assert(#fields == 3, "expected 3 fields")
    assert(fields[1].name == "id", "field[1] should be id")
    assert(fields[2].name == "name", "field[2] should be name")
    assert(fields[3].name == "num", "field[3] should be num")
    local row = pg:GetResultRow()
    assert(row ~= nil, "expected a row")
    assert(type(row[1]) == "number", "id should be integer")
    assert(row[2] == "hello", "name should be hello")
    pg:GetResultRow()
end)

run("Postgres transaction BEGIN COMMIT", function()
    local ok, err = pg:Query("BEGIN")
    assert(ok, "BEGIN failed: " .. tostring(err))
    local r1 = pg:GetResult()
    assert(r1 ~= nil and type(r1) == "table", "BEGIN should return empty table")

    local ok2, e2 = pg:Query("INSERT INTO kitsune_test (name, num) VALUES ('txtest', 77)")
    assert(ok2, "INSERT in tx failed: " .. tostring(e2))
    pg:GetResult()

    local ok3, e3 = pg:Query("SELECT name, num FROM kitsune_test WHERE name = 'txtest'")
    assert(ok3, "SELECT in tx failed: " .. tostring(e3))
    local rows = pg:GetResult()
    assert(rows and #rows == 1, "expected 1 row inside transaction")
    assert(rows[1][1] == "txtest" and rows[1][2] == 77, "row data mismatch in transaction")

    local ok4, e4 = pg:Query("ROLLBACK")
    assert(ok4, "ROLLBACK failed: " .. tostring(e4))
    pg:GetResult()

    local ok5, e5 = pg:Query("SELECT name FROM kitsune_test WHERE name = 'txtest'")
    assert(ok5, "SELECT after rollback failed: " .. tostring(e5))
    local rows2 = pg:GetResult()
    assert(rows2 and #rows2 == 0, "expected 0 rows after ROLLBACK, got " .. tostring(rows2 and #rows2))
end)

run("Postgres IsBusy is false after GetResult", function()
    local ok = pg:Query("SELECT 1")
    assert(ok, "Query failed")
    pg:GetResult()
    assert(pg:IsBusy() == false, "IsBusy should be false after GetResult")
end)

run("Postgres.EscapeValue escapes a string", function()
    local escaped = pg:EscapeValue("O'Reilly")
    assert(type(escaped) == "string", "EscapeValue should return string")
    assert(escaped:find("O") and escaped:find("Reilly"), "escaped string should still contain the original text")
    assert(escaped:sub(1, 1) == "'", "PQescapeLiteral should wrap with leading quote, got: " .. escaped)
    assert(escaped:sub(-1) == "'", "PQescapeLiteral should wrap with trailing quote, got: " .. escaped)
    assert(escaped:find("''"), "single quote should be doubled inside, got: " .. escaped)
end)

run("Postgres returns error on bad query", function()
    local ok, err = pg:Query("SELECT * FROM table_that_does_not_exist_ever")
    assert(ok, "Query dispatch failed: " .. tostring(err))
    local result, qerr = pg:GetResult()
    assert(result == nil, "expected nil result for bad query")
    assert(type(qerr) == "string", "expected error string, got: " .. type(qerr))
end)

run("Postgres.Query DROP TABLE cleanup", function()
    local ok, err = pg:Query("DROP TABLE IF EXISTS kitsune_test")
    assert(ok, "Query failed: " .. tostring(err))
    local result, qerr = pg:GetResult()
    assert(result ~= nil or qerr == nil, "DROP TABLE error: " .. tostring(qerr))
end)

run("Postgres.Close cleans up", function()
    pg:Close()
end)